hostspace/sop/src/Form/SopDeleteForm.php
<?php

/**
 * @file
 * Contains \Drupal\sop\Form\SopDeleteForm.
 */

namespace Drupal\sop\Form;

use Drupal\Core\Entity\ContentEntityConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Provides the part delete confirmation form.
 */
class SopDeleteForm extends ContentEntityConfirmFormBase {

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Are you sure you want to delete this sop ? Module: %module, Id: %id', array(
      '%module' => $this->entity->get('module')->value,
      '%id' => $this->entity->get('sid')->value,
    ));
  }
  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    // Point to the entity of which this sop.
    return new Url('admin.sop_task.list');
  }
  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('This sop will be delete. Please confirm this sop has not any been used storage.');
  }
  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Delete');
  }
  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    // Delete the sop task(as server, room, ...) entity first.
    $entity = $this->entity;
    $module = $entity->get('module')->value;
    $sid = $entity->get('sid')->value;
    $sop_task = entity_load($module, $sid);

    // 删除之前，记录日志.
    $sop_task->other_status = 'sop_common_task';
    $entity->other_status = 'sop_specified_task';
    HostLogFactory::OperationLog('sop')->log($sop_task, 'delete');
    HostLogFactory::OperationLog('sop')->log($entity, 'delete');
    // Delete the sop task.
    $sop_task->delete();
    // Delete the sop and its replies.
    $entity->delete();

    drupal_set_message($this->t('The sop have been deleted.'));
    $form_state->setRedirectUrl($this->getCancelUrl());
  }

}

hostspace/sop/templates/admin-handle-task-server-hostclient-info.html.twig
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th colspan=4 class="bg-primary">附加业务</th>
    </tr>
    <tr>
      <th>ID</th>
      <th>类型</th>
      <th>名称</th>
    </tr>
  </thead>
  <tbody>
    {% for business in handle_info.business %}
    <tr>
      <td scope="row">{{ loop.index }}</td>
      <td>{{business.name}}</td>
      <td>{{business.value}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

hostspace/sop/templates/sop-task-failure-detail.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-11">
    <div class="row">
      <div class="col-xs-8">
        <div class="row">
          <div class="col-xs-6">
            {{ form.mips }}
          </div>
          <div class="col-xs-6">
            {{ form.created }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4">
            {{ form.sop_type }}
          </div>
          <div class="col-xs-4">
            {{ form.uid }}
          </div>
          <div class="col-xs-4">
            {{ form.solving_uid }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            {{ form.diff_time }}
          </div>
          <div class="col-xs-6">
            {{ form.level }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <div class="row">
              <div class="col-xs-6">
                {{ form.base_description }}
              </div>
              <div class="col-xs-6">
                {{ form.result_description }}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="row">
          <div class="col-xs-12">
            {{ form.markup_sop_status }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.description }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.deal }}
            {{ form.question }}
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      {{ form.actions }}
    </div>
  </div>
</div>

hostspace/sop/templates/sop-task-failure-form.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-8">
    <div class="row">
      <div class="col-xs-8">
        {{ form.mips }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8">
        {{ form.client_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.os }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.description }}
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-8">
    {{ form.actions }}
  </div>
</div>

hostspace/sop/templates/sop-task-iband-detail.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
{{form.room_check}}
{{form.room}}
<div class="row">
  <div class="col-xs-8">
    <div class="row">
      <div class="col-xs-4">
        {{ form.mips }}
      </div>
      <div class="col-xs-4">
        {{ form.client_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.created }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.bips }}
      </div>
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.aips }}
      </div>
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.sips }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.pid }}
      </div>
      <div class="col-xs-4">
        {{ form.equipment_date }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.pre_solving_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_op_type }}
      </div>
      <div class="col-xs-4">
        {{ form.os }}
      </div>

    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="row">
          <div class="col-xs-12">
            {{ form.tech_iband_edit_info }}
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="row">
          <div class="col-xs-12">
            {{ form.tech_iband_check_info }}
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="row">
          <div class="col-xs-12">
            {{ form.tech_edit_info }}
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {{ form.actions }}
    </div>
  </div>
  <div class="col-xs-4">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <p class="text-primary">{{ form.markup_sop_room }}</p>
            <p class="text-info">{{ form.markup_sop_status }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <p class="text-danger">{{ form.markup_server_status }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <p class="text-warning">{{ form.client_description }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.additonal_bussiness }}
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.edit_info.business_ip.bip_segment }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.bip_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_wrapper }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_text }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4 col-xs-offset-3">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_submit }}
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        {{ form.description }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.result_description }}
      </div>
    </div>
  </div>
</div>

hostspace/sop/templates/sop-task-iband-form.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-8">
    <div class="row">
      <div class="col-xs-4">
        {{ form.mips }}
      </div>
      <div class="col-xs-4">
        {{ form.client_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.bips }}
      </div>
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.aips }}
      </div>
      <div class="col-xs-4">
        {{ form.edit_info.business_ip.sips }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8">
        {{ form.description }}
      </div>
      <div class="col-xs-4">
        <div class="row">
          <br />
          {{ form.sop_op_type }}
        </div>
        <div class="row">
          <br/>
          {{ form.actions }}
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="row">
      <div class="col-xs-6">
        {{ form.set_active }}
      </div>
      <div class="col-xs-5">
        {{ form.bip_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-11">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_wrapper }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-11">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_text }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-11">
        {{ form.edit_info.business_ip.ipb_search.ipb_search_submit }}
      </div>
    </div>
  </div>
</div>

hostspace/sop/templates/sop-task-machine-detail.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-11">
    <div class="row">
      <div class="col-xs-4">
        {{ form.mips }}
      </div>
      <div class="col-xs-4">
        {{ form.client_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_op_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.uid }}
      </div>
      <div class="col-xs-4">
        {{ form.solving_uid }}
      </div>
      <div class="col-xs-4">
        {{ form.changed }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.description }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.actions }}
      </div>
  </div>
</div>

hostspace/sop/templates/sop-task-machine-form.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-8">
    <div class="row">
      <div class="col-xs-7">
        <div class="row">
          <div class="col-xs-11">
            {{ form.mips }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-11">
            {{ form.description }}
          </div>
        </div>
      </div>
      <div class="col-xs-5">
        <div class="row">
          <div class="col-xs-12">
            {{ form.client_uid }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.sop_op_type }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-11">
            {{ form.actions }}
          </div>
        </div>

      </div>
    </div>

  </div>
</div>

hostspace/sop/templates/sop-task-not-found-detail.html.twig
fdsafd

hostspace/sop/templates/sop-task-room-detail.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-11">
    <div class="row">
      <div class="col-xs-8">
        <div class="row">
          <div class="col-xs-4">
            {{ form.mips }}
          </div>
          <div class="col-xs-4">
            {{ form.client_uid }}
          </div>
          <div class="col-xs-4">
            {{ form.sop_type }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4">
            {{ form.pid }}
          </div>
          <div class="col-xs-4">
            {{ form.cabinet }}
          </div>
          <div class="col-xs-4">
            {{ form.port }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4">
            {{ form.created }}
          </div>
          <div class="col-xs-4">
            {{ form.uid }}
          </div>
          <div class="col-xs-4">
            {{ form.solving_uid }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.description }}
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="row">
          <div class="col-xs-12">
            {{ form.base_description }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.result_description }}
          </div>
        </div>
      </div>
    </div>
    <div class="row">
        {{ form.actions }}
    </div>
  </div>
</div>

hostspace/sop/templates/sop-task-room-form.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-8">
    <div class="row">
      <div class="col-xs-4">
        {{ form.mip }}
      </div>
      <div class="col-xs-4">
        {{ form.sop_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        {{ form.pid }}
      </div>
      <div class="col-xs-4">
        {{ form.cabinet }}
      </div>
      <div class="col-xs-4">
        {{ form.port }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        {{ form.description }}
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="row">
      <div class="col-xs-11">
        <h5>提示</h5>
        1. 选择管理IP<br/>
        *. 管理IP是全部上柜服务器的管理IP<br/>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    {{ form.actions }}
  </div>
</div>

hostspace/sop/templates/sop-task-server-detail.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-9">
    <div class="row">
      <div class="col-xs-3">
        {{ form.mip }}
      </div>
      <div class="col-xs-3">
        {{ form.client_uid }}
      </div>
      <div class="col-xs-3">
        {{ form.pid }}
      </div>
      <div class="col-xs-3">
       {{ form.sop_type }}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <div class="row">
          <div class="col-xs-12">
            {{ form.bips }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.management_card }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.additonal_bussiness }}
          </div>
        </div>
      </div>
      <div class="col-xs-7">
        <div class="row">
         <div class="col-xs-6">
            {{ form.os }}
          </div>
          <div class="col-xs-6">
            {{ form.bandwidth }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            {{ form.created }}
          </div>
          <div class="col-xs-6">
            {{ form.sop_op_type }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            {{ form.uid }}
          </div>
          <div class="col-xs-6">
            {{ form.solving_uid }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.base_description }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.description }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="row">
      <div class="col-xs-11">
        {{ form.result_description }}
      </div>
    </div>

  </div>
</div>
<div class="row">
  <div class="col-xs-3">
    <button class="btn btn-success" type="submit">修改</button>
  </div>
  <div class="col-xs-3">
    <button class="btn btn-danger" type="submit">审核异常</button>
  </div>
  <div class="col-xs-3">
    <button class="btn btn-primary" type="submit">接受工单</button>
  </div>
  <div class="col-xs-3">
    <button class="btn btn-warning" type="submit">撤消工单</button>
  </div>
</div>

hostspace/sop/templates/sop-task-server-form.html.twig
{{form.form_build_id}}
{{form.form_token}}
{{form.form_id}}
<div class="row">
  <div class="col-xs-9">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4">
            {{ form.mips }}
          </div>
          <div class="col-xs-4">
            {{ form.client_uid }}
          </div>
          <div class="col-xs-4">
            {{ form.sop_type }}
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="row">
            <div class="col-xs-12">
              {{ form.edit_info.business_ip.bips }}
            </div>
        </div>
      </div>
      <div class="col-xs-8">
        <div class="row">
          <div class="col-xs-12">
            {{ form.pid }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.bip_type }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.os }}
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            {{ form.bandwidth }}
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-4">
            {{ form.edit_info.business_ip.ipb_search.ipb_search_wrapper }}
          </div>
          <div class="col-xs-8">
            <div class="row">
              <div class="col-xs-9">
                {{ form.edit_info.business_ip.ipb_search.ipb_search_text }}
              </div>
              <div class="col-xs-3">
                <br/>
                <br/>
                {{ form.edit_info.business_ip.ipb_search.ipb_search_submit }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="row">
      <div class="col-xs-11">
        {{ form.description }}
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-offset-5">
    {{ form.actions }}
  </div>
</div>